project:
  type: website
  output-dir: docs

website:
  title: "EXDATA"
  navbar:
    left:
      - href: index.qmd
        text: Welcome| স্বাগতম
      - href: vision.qmd
        text: Vision| আমাদের লক্ষ্য
      - href: service.qmd
        text: Services| সেবা
      - href: platform.qmd
        text: Platform| প্ল্যাটফর্ম
      - href: team.qmd
        text: Research team| গবেষণা দল
      
  page-footer: 
    left: "Copyright 2025, EXDATA" 

format:
  html:
    theme: quartz
    toc: false
    mainfont: Times New Roman
    fontsize: 1.1em
    linestretch: 1.1
    embed-resources: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

editor: visual

